import React from "react";
export const list = [
  {
    title: "React",
    url: "https://facebook.github.io/react/",
    author: " Jordan Walke",
    num_comments: 3,
    points: 4,
    objectID: 0,
  },
  {
    title: "Redux",
    url: "https://github.com/reactjs/redux",
    author: " Dan Abramov, Andrew Clark",
    num_comments: 2,
    points: 5,
    objectID: 51,
  },
  {
    title: "Haleem",
    url: "http://localhost:3000",
    author: " Haleem Salahi",
    num_comments: 25,
    points: 66,
    objectID: 52,
  },

  {
    objectID: "1",
    title: "distinctio voluptatem.",
    url: "http://localhost3000",
    author: "Jon Flatley PhD",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "2",
    title: "s eos deserunt.",
    url: "http://localhost3000",
    author: "Adalberto Glover",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "3",
    title: " quia omnis tempora.",
    url: "http://localhost3000",
    author: "Ms. Cynthia Lind Sr.",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "4",
    title: " blanditiis.",
    url: "http://localhost3000",
    author: "Prof. Alan Walsh I",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "5",
    title: " ea.",
    url: "http://localhost3000",
    author: "Dr. Candido Kuhn II",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "6",
    title: " nihil et.",
    url: "http://localhost3000",
    author: "Andy Little Jr.",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "7",
    title: "it molestias facere.",
    url: "http://localhost3000",
    author: "Maida Sauer",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "8",
    title: "aque.",
    url: "http://localhost3000",
    author: "Dr. Lura Hammes",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "9",
    title: "issimos id.",
    url: "http://localhost3000",
    author: "Myrtice Kshlerin",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "10",
    title: "rem voluptatem corrupti a.",
    url: "http://localhost3000",
    author: "Wava Schuppe",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "11",
    title: "rehenderit aut voluptatem sit nam quia.",
    url: "http://localhost3000",
    author: "Evangeline Murphy",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "12",
    title: "que.",
    url: "http://localhost3000",
    author: "Delaney Watsica",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "13",
    title: "pudiandae sint ab et.",
    url: "http://localhost3000",
    author: "Miss Tressie Schowalter Jr.",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "14",
    title: "ecati fugiat.",
    url: "http://localhost3000",
    author: "Josianne Huels",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "15",
    title: "ssitatibus sed et eum quis.",
    url: "http://localhost3000",
    author: "Marilyne Moen DVM",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "16",
    title: "r aut.",
    url: "http://localhost3000",
    author: "Amparo Ward",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "17",
    title: "rem temporibus delectus.",
    url: "http://localhost3000",
    author: "Dr. Coleman Wolf",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "18",
    title: "delectus unde ab perspiciatis.",
    url: "http://localhost3000",
    author: "Lenora Leffler",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "19",
    title: " voluptate cum.",
    url: "http://localhost3000",
    author: "Gianni VonRueden V",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "20",
    title: "netur.",
    url: "http://localhost3000",
    author: "Mr. Wilfredo Schimmel II",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "21",
    title: "Hello world",
    url: "http://localhost3000",
    author: "Ms. Edyth O'Conner",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "22",
    title: "jordon",
    url: "http://localhost3000",
    author: "Dr. Cydney Veum Jr.",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "23",
    title: "quae consectetur.",
    url: "http://localhost3000",
    author: "Lottie Stamm",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "24",
    title: "equatur magni qui facere et.",
    url: "http://localhost3000",
    author: "Libbie Becker",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "25",
    title: "tempora.",
    url: "http://localhost3000",
    author: "Mr. Claude Labadie",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "26",
    title: "quia iste possimus similique.",
    url: "http://localhost3000",
    author: "Annie Doyle",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "27",
    title: "uas ut non.",
    url: "http://localhost3000",
    author: "Kiera Huel",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "28",
    title: "t eos.",
    url: "http://localhost3000",
    author: "Patricia Mraz",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "29",
    title: "que beatae.",
    url: "http://localhost3000",
    author: "Randy Keeling V",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "30",
    title: " reiciendis dolorem.",
    url: "http://localhost3000",
    author: "Prof. Alberto Bahringer",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "31",
    title: "que corporis odit.",
    url: "http://localhost3000",
    author: "Gina Zieme",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "32",
    title: "a vero quia.",
    url: "http://localhost3000",
    author: "Dr. Esta Kirlin Jr.",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "33",
    title: "modi.",
    url: "http://localhost3000",
    author: "Rachael Will",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "34",
    title: "uid eveniet odit.",
    url: "http://localhost3000",
    author: "Mr. Layne Harvey",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "35",
    title: " consequatur blanditiis.",
    url: "http://localhost3000",
    author: "Uriah Bruen",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "36",
    title: "os nesciunt dolores laborum et.",
    url: "http://localhost3000",
    author: "Albert Goyette",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "37",
    title: " aut asperiores consequatur.",
    url: "http://localhost3000",
    author: "Cornell Feest",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "38",
    title: "juatur dolores.",
    url: "http://localhost3000",
    author: "Helen Johns",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "39",
    title: "ed.",
    url: "http://localhost3000",
    author: "Dr. Velva Smitham",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "40",
    title: "pellat nostrum maxime.",
    url: "http://localhost3000",
    author: "Mrs. Rosina Rolfson",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "41",
    title: " omnis cum hic.",
    url: "http://localhost3000",
    author: "Danyka Erdman Jr.",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "42",
    title: " facere provident.",
    url: "http://localhost3000",
    author: "Prof. Giuseppe Hoeger III",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "43",
    title: "itia earum soluta est possimus quam.",
    url: "http://localhost3000",
    author: "Miss Emilie Kertzmann",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "44",
    title: ".",
    url: "http://localhost3000",
    author: "Myrtice Stiedemann",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "45",
    title: "uos sed.",
    url: "http://localhost3000",
    author: "Stephanie Murazik",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "46",
    title: "ptatum architecto aut ab.",
    url: "http://localhost3000",
    author: "Prof. Nicholaus Williamson Jr.",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "47",
    title: "t sit.",
    url: "http://localhost3000",
    author: "Lavon Abshire",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "48",
    title: "quidem.",
    url: "http://localhost3000",
    author: "Harley Rogahn",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "49",
    title: "m ea accusamus velit.",
    url: "http://localhost3000",
    author: "Marlen Schowalter",
    num_comments: 25,
    points: 12,
  },
  {
    objectID: "50",
    title: " est ut enim voluptatem.",
    url: "http://localhost3000",
    author: "Prof. Horacio Hintz Sr.",
    num_comments: 25,
    points: 12,
  },
];
